package:
  name: jobqueues
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
   path: ../..

build:
  script:
    - "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python
    - protocolinterface
    - psutil
    - pyyaml
    - jinja2
    - versioneer==0.28 

  run:
    - python
    - protocolinterface
    - psutil
    - pyyaml
    - jinja2


about:
  home: https://github.com/acellera/jobqueues/
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
  summary: Unified interface for interacting with queueing systems.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - stefdoerr
