sudo: required
dist: xenial
matrix:
  include:
    - os: linux
      language: python
      python:
        - '3.6'
      env: OSNAME=Linux CONDA_PY=3.6
    - os: linux
      language: python
      python:
        - '3.7'
      env: OSNAME=Linux CONDA_PY=3.7
    # - os: osx
    #   language: python
    #   python:
    #     - '3.6'
    #   env: OSNAME=Darwin CONDA_PY=3.6


env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
    - PYTHONHASHSEED=0

before_install:
  - source ci/travis/install_miniconda.sh

script:
  - source activate test
  - pip install --user --upgrade -q setuptools wheel twine
  # Insert version number and dependencies into pip and conda recipes
  - python ci/travis/insert_placeholder_values.py
  # Install the package locally
  - pip install .
  # Run tests
  - pip install -q codecov coverage
  - coverage run -m unittest discover --start-directory ./jobqueues --pattern "*.py"
  - echo "Finished tests"

after_success:
  - echo "Attempting codecov statistics upload"
  - codecov

deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
      tags: true
      branch: master
    user: stefdoerr
    password: # To produce encrypted pass use `travis encrypt "dont-escape-this-password" -r Acellera/jobqueues`
      secure: VURwO0NtBB6axQyKy6ZKf+OFApuViqttcQzOIj/AE5SLdUodgSdx49CfyAU5B+pD5xtuR76k4DTKNRE2RSkLQ3fNjCSNZwHnUrW1kwboFIc4HVD+HiPETOjg7/aaQQqdu3zh8Frl4zRcybJZpRgYEbylrSKOxtFgtborjH9tjiYXmvqWjnl7pP6qCOFPaEqg6jLnj3OYReUoKpQu8BAggUiQ4EpjFAFp0sld1P3dyTfG+pBHKMOTAPli3fQTpkkt4eFN5hdLSwzfQTHq+3E5pPV1exzzlwBgO3vLRMqDtKLcn/PkOZZeHaFJfbz3Nsa9AuNera4avtG0nGJaNCya1/1G1Q7jQofn0n570uZu9z+5gkNY5D23bWP5HCDE8hGmOPV6hEFiw/QBkc4n6nDiN1RzJ312oHAYm4ufIQM/V6l61gUQ+B2oeg3dlSrvJkkGj5Kci6/xZjXbJB78r6IoC0Ps4T1u3EVNsG+JW/Gt7GLWYaquxg7aF672kTuOpdavBZAKt2JSitg3jFSAkofWeQ6pAchpaaUEw2lICz++3NS1fGr++bbi8PoaRuQzjJSkrZoH2lMyK27iuI43YQD6YEJYg0PscCw/VUyzF6d1vAr/9RuAtSVEX54UUFW3rmVOShImHrQXW1NbMFoG2JH3bkyzjKpUp31EhzBpe3hxnWI=
    skip_existing: true
    #server: https://test.pypi.org/legacy/
  - provider: script
    skip_cleanup: true
    script: bash ./ci/travis/deploy.sh
    on:
      tags: true
      branch: master
