name: Upload Python Package

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    defaults: # Needed for conda
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: acellera,conda-forge,defaults

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine flake8

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test package
        run: |
          pip install .
          pip install -q codecov coverage pytest
          coverage run -m pytest ./jobqueues/ --ignore=jobqueues/celeryfiles/
          pytest ./tests

      - name: Build PyPI 📦
        run: |
          pip install build twine versioneer==0.28 
          python -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PUBLIC_PYPI_API_TOKEN }}
          skip_existing: true

      - name: Build and publish conda package
        run: |
          mamba install anaconda-client rattler-build -y -q
          python package/jobqueues/insert_placeholder_values.py

      - name: Build conda package
        run: rattler-build build --recipe ./package/jobqueues/recipe.yaml --output-dir /tmp/pkg/

      - name: Upload to conda
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN_BASIC }} upload -u acellera /tmp/pkg/noarch/jobqueues-*.conda
