name: Upload Python Package

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.6", "3.7"]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test package
      run: |
        pip install .
        pip install -q codecov coverage pytest
        coverage run -m pytest ./jobqueues/ --ignore=jobqueues/celeryfiles/
        codecov

    - name: Set version in __init__.py
      run: |
        export TAG_DESCRIBE=$(git describe)
        export BUILD_VERSION=$(echo $TAG_DESCRIBE | sed 's/-/ /g'  | awk '{print $1}')
        sed -i "s/__version__ = \"unpackaged\"/__version__ = \"$BUILD_VERSION\"/" jobqueues/__init__.py

    - name: Build and publish
      env:
        TWINE_USERNAME: stefdoerr
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
      continue-on-error: true

    - name: Build and publish conda package
      run: |
        export TAG_DESCRIBE=$(git describe)
        export BUILD_VERSION=$(echo $TAG_DESCRIBE | sed 's/-/ /g'  | awk '{print $1}')
        export BUILD_NUMBER=0
        $CONDA/bin/conda install anaconda-client conda-build -y -q
        $CONDA/bin/conda build --python ${{ matrix.python-version }} --no-include-recipe package/jobqueues -c acellera
        $CONDA/bin/anaconda -t ${{ secrets.ANACONDA_TOKEN_BASIC }} upload -u acellera $CONDA/conda-bld/linux-64/jobqueues-*.tar.bz2